version: '3.8'

services:
  auth_service_jockey:
    container_name: auth_service_jockey
    image: auth_service_jockey
    ports:
      - "4300:4300"
    env_file:
      - .env
    restart: unless-stopped
